### PR TITLE
update(zoocart): add info about groups assigning

### PR DESCRIPTION
**Pull request by ameli90**
https://github.com/JOOlanders/documentation/issues/55

Please merge when the branch ZOOcart:feature/autoassign_usergroups will be merged.

### CODE REVIEW

**Comment by ameli90** [comment]
Need someone to review the text

**Comment by ddavidov** [comment]
Small note: There are mysterious "Buy" element on that screenshots. Could be not clear enough for some customers, that it's a **ZOOcartElement**, probably Add to cart would be better IMHO.

**Comment by ddavidov** [comment]
Is this chapter totally completed for now?

**Comment by ameli90** [comment]
Renamed the element to ZOOcart element. Anyway it shows the element type in the element settings.

**Comment by ddavidov** [comment]
Ok, agree )

**Comment by dguzenko** [comment]
"For the subscription item has additional select box with groups to remove." Change to "The subscription item has additional select box with groups to remove."

**Comment by ameli90** [comment]
thanks, done

**Comment by miljan-aleksic** [comment]
Remove the ZOOcart Element red title, it's redundant

**Comment by ameli90** [comment]
removed

**Pull request merged**
